- hosts: local
  connection: local
  vars_files:
    - 'vars_{{ package_manager }}.yaml'
  tasks:
    - name: create directory for dotfiles repo
      ansible.builtin.command: "mkdir /home/{{ user }}/.dotfiles"
      args:
        creates: "/home/{{ user }}/.dotfiles"
    - name: create .gitignore
      ansible.builtin.shell: "echo '.dotfiles' >> /home/{{ user }}/.gitignore"
      args:
        creates: "/home/{{ user }}/.gitignore"
    - name: clone dotfiles repo
      ansible.builtin.git:
        repo: 'https://github.com/z1lq/.dotfiles'
        dest: "/home/{{ user }}/.dotfiles"
        bare: yes
    - name: checkout dotfiles repo
      ansible.builtin.shell: git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout
    - name: disable showing untracked files
      ansible.builtin.shell: git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
