- hosts: local
  connection: local
  vars_files:
    - 'vars_{{ package_manager }}.yaml'
  tasks:
    - name: download go
      get_url:
        url: https://go.dev/dl/go1.21.3.linux-amd64.tar.gz
        dest: '/tmp/golang.tar.gz'
    - name: remove existing version
      become: yes
      become_user: root
      ansible.builtin.command: "rm -rf /usr/local/go"
    - name: install go
      become: yes
      become_user: root
      ansible.builtin.command: "tar -C /usr/local -xzf /tmp/golang.tar.gz"
