- hosts: local
  connection: local
  vars_files:
    - 'vars_{{ package_manager }}.yaml'
  tasks:
    - name: download obsidian
      get_url:
        url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.4.16/Obsidian-1.4.16.AppImage
        dest: '/home/{{ user }}/bin/obsidian'
        mode: '0755'
