- name: enable ghostty copr
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: pgdev/ghostty

- name: install ghostty
  ansible.builtin.dnf:
    name: "ghostty"
    state: present
