- name: install dive
  ansible.builtin.shell: |
    DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.rpm
    rpm -i dive_${DIVE_VERSION}_linux_amd64.rpm
- name: install lazydocker
  ansible.builtin.shell: |
    asdf plugin add lazydocker https://github.com/comdotlinux/asdf-lazydocker.git
    asdf install lazydocker latest
    asdf global lazydocker latest
